# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Make gradlew executable
#        run: chmod +x gradlew


      # Run lint on debug build
      - name: Run Lint
        run: echo Run Lint
#        run: ./gradlew lintDebug

      # Upload lint report html file on github action artifact
#      - name: Upload html test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html


  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Make gradlew executable
#        run: chmod +x gradlew

      - name: Run test
        run: echo Run test
#        run: ./gradlew test

#      - name: Upload test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: unit_test_report
#          path: app/build/reports/tests/testDebugUnitTest/



  instrumentation-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run test
        run: echo Instrument test

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Make gradlew executable
#        run: chmod +x gradlew

#      - name: Run espresso test
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 33
#          script: ./gradlew connectedDebugAndroidTest
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: instrumentation_test_report
#          path: app/build/reports/androidTests/connected/



  sonar:
    name: SonarCube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Set up jdk 17
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Build the project
        run: ./gradlew build --warning-mode all

      - name: Run SonarQube Scan
        run: ./gradlew sonarqube
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_LOGIN: "2996ab54d274cc8d18f428fa81e493583b80250e"
          SONAR_PROJECT_KEY: "rishabhparihar77_rishabh_e_commerce_app"
          SONAR_ORGANIZATION: "rishabhparihar77"
#
#      - name: SonarCloud Scan
#        run: ./gradlew app:sonarqube -Dsonar.login=${{secrets.SONAR_TOKEN}}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




